# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcwQT2HT2QLdmUbBgYCCJMyP0QrvCLhF
"""

import pandas as pd
import requests
import os
import time
import gc
from google.colab import drive

drive.mount('/content/drive')

mapbox_token = "pk.eyJ1IjoiYXl1c2hyYWowMTExIiwiYSI6ImNtank3MHBsaTAzejMzZHNlYTZoaWU3cjQifQ.bEPfqH4f5pvDISAKv2MOWQ"

# Folder where images will be saved in your Drive
base_drive_path = "/content/drive/MyDrive/Mapbox_Dataset_Zoom17.5"

# The two files to process
tasks = [
    ("train (1).csv", "train_images"),
    ("test (2).csv", "test_images")
]

zoom_level = 17.5
width = 600
height = 600
retina = "@2x"   # High Quality
style_id = 'satellite-v9'
username = 'mapbox'

for csv_file, folder_name in tasks:

    output_folder = os.path.join(base_drive_path, folder_name)
    print(f"\n--- Starting {csv_file} -> Saving to: {output_folder} ---")

    # Create the folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Load the CSV
    try:
        df = pd.read_csv(csv_file)
        print(f"Loaded {len(df)} locations from {csv_file}")
    except FileNotFoundError:
        print(f"Skipping {csv_file} (File not found!)")
        continue

    # Loop through every house in the list
    for index, row in df.iterrows():

        house_id = row['id']
        filename = f"{output_folder}/{house_id}.jpg"

        # SKIP if we already have it (This allows you to pause/resume)
        if os.path.exists(filename):
            continue

        # Get Coordinates
        lat = row['lat']
        lon = row['long']

        # Build URL
        url = f"https://api.mapbox.com/styles/v1/{username}/{style_id}/static/{lon},{lat},{zoom_level}/{width}x{height}{retina}?access_token={mapbox_token}"

        try:
            response = requests.get(url, timeout=10)

            if response.status_code == 200:
                # Save the image
                with open(filename, 'wb') as f:
                    f.write(response.content)
            else:
                print(f"Error downloading {house_id}: Status {response.status_code}")

        except Exception as e:
            print(f"Connection failed for {house_id}: {e}")
            time.sleep(1)


        # Every 100 images, clear RAM
        if index % 100 == 0:
            gc.collect()
            print(f"Progress: {index}/{len(df)} images saved...")

print("\nAll downloads finished successfully!")

import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

base_drive_path = "/content/drive/MyDrive/Mapbox_Dataset_Zoom17.5"

# Define the pairs to check
tasks = [
    ("train (1).csv", "train_images"),
    ("test (2).csv", "test_images")
]

for csv_file, folder_name in tasks:

    print(f"\nChecking {folder_name}...")


    try:
        df = pd.read_csv(csv_file)
        # Convert IDs to string because filenames are strings
        expected_ids = set(df['id'].astype(str))
    except FileNotFoundError:
        print(f"Error: Could not read {csv_file}")
        continue

    folder_path = os.path.join(base_drive_path, folder_name)

    if os.path.exists(folder_path):
        files_found = os.listdir(folder_path)
        actual_ids = set([f.replace('.jpg', '') for f in files_found if f.endswith('.jpg')])
    else:
        print(f"Error: Folder not found at {folder_path}")
        actual_ids = set()

    missing_ids = expected_ids - actual_ids
    print("-" * 30)
    print(f"Total Expected: {len(expected_ids)}")
    print(f"Total Found:    {len(actual_ids)}")
    print(f"MISSING:        {len(missing_ids)}")
    print("-" * 30)

    if len(missing_ids) > 0:
        print("First 5 missing IDs:", list(missing_ids)[:5])
        print("You should re-run the download script to fetch these.")
    else:
        print(" 100% Complete! No images missing.")